### ISSUE TITLE
April 2018 Update still/already supported?

### ISSUE THREAD

**Issue by Eddi2015** [adolfintel/Windows10-Privacy#14]
The title says spring creators update. Anyway, there are new options such as the possibility to delete diagnostic information. Maybe that can be automated?

**Comment by adolfintel** [comment]
Yes I know they later renamed it to April 2018 update, but it's updated. Not that anything changed between 17133 and 17134.
If you follow this guide you shouldn't need to manually delete any diagnostic data, since the services collecting it are removed.
I also made some attempts at automating the whole process without too much success, a user made a semi-automated autohotkey script (see #13).

I'm closing the issue. If that doesn't answer your question, you can still reply.
