### ISSUE TITLE
Breaking things

### ISSUE THREAD

**Issue by legendarynacar** [adolfintel/Windows10-Privacy#8]
Hey,

Is there any possibility that breaks in my system and force me to reinstall after I followed the guide?

**Comment by adolfintel** [comment]
As mentioned in the guide, UWP will be compromised (not entirely removed, but several features are removed so there are no guarantees that manually installed UWP apps will run). Signing in with a Microsoft account is also broken of course, but that's intentional.
I'm not aware of anything else broken by the guide.

**Comment by legendarynacar** [comment]
Yeah, I got those  points of losing features of windows services. But main concern is about Operation System malfunction. And I wonder how it will affect my privacy if I keep using Linux Subsystem?

**Comment by adolfintel** [comment]
The system is stable, I've been doing this since 2015 and I never had any real issue.
The Linux Subsystem needs the Store to download distros, so unless you're planning on doing the upgrades in other ways, you should use a VM for that, as I do. Also, Tinywall doesn't have a way to unblock individual processes in the Linux Subsystem.
